declare module "System/Globalization" {
    export enum NumberStyles {
        None,
        AllowLeadingWhite,
        AllowTrailingWhite,
        AllowLeadingSign,
        AllowTrailingSign,
        AllowParentheses,
        AllowDecimalPoint,
        AllowThousands,
        AllowExponent,
        AllowCurrencySymbol,
        AllowHexSpecifier,
        Integer,
        HexNumber,
        Number,
        Float,
        Currency,
        Any,
    }

    export enum UnicodeCategory {
        UppercaseLetter,
        LowercaseLetter,
        TitlecaseLetter,
        ModifierLetter,
        OtherLetter,
        NonSpacingMark,
        SpacingCombiningMark,
        EnclosingMark,
        DecimalDigitNumber,
        LetterNumber,
        OtherNumber,
        SpaceSeparator,
        LineSeparator,
        ParagraphSeparator,
        Control,
        Format,
        Surrogate,
        PrivateUse,
        ConnectorPunctuation,
        DashPunctuation,
        OpenPunctuation,
        ClosePunctuation,
        InitialQuotePunctuation,
        FinalQuotePunctuation,
        OtherPunctuation,
        MathSymbol,
        CurrencySymbol,
        ModifierSymbol,
        OtherSymbol,
        OtherNotAssigned,
    }

    export enum DateTimeStyles {
        None,
        AllowLeadingWhite,
        AllowTrailingWhite,
        AllowInnerWhite,
        AllowWhiteSpaces,
        NoCurrentDateDefault,
        AdjustToUniversal,
        AssumeLocal,
        AssumeUniversal,
        RoundtripKind,
    }
}